{% set name = "hipace" %}
{% set version = "23.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Hi-PACE/hipace/archive/v{{ version }}.tar.gz
  sha256: 1c740c925294bacec2b7c27778339d71528a4bd1a81e051a9cc47e44b4cd0cdf
  patches:
    # Fix External AMReX & pyAMReX Builds
    - 1031.patch

build:
  # Prevent conda-build from deciding to build for each python version when hipace doesn't depend on python
  skip: true  # [py != 310]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang         # [win]
    - cmake
    - lld           # [win]
    - make          # [unix]
    - ninja         # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx]
    - intel-openmp  # [win]
    - pkgconfig
  host:
    - amrex >={{ version }}
    - fftw =*=nompi_*
    - openpmd-api =*=nompi_*

test:
  requires:
    - bash    # [build_platform == target_platform and not win]
    - python  # [build_platform == target_platform]
    - numpy   # [build_platform == target_platform]
    - openpmd-api =*=nompi_*  # [build_platform == target_platform]
    - openpmd-viewer          # [build_platform == target_platform]
    - pandas  # [build_platform == target_platform]
    - pytest  # [build_platform == target_platform]
    - python  # [build_platform == target_platform]
    - scipy   # [build_platform == target_platform]
  source_files:
    - examples/
    - tests/
  files:
    - test.sh   # [unix]
    - test.bat  # [win]
  commands:
    - test -f ${PREFIX}/bin/hipace.NOMPI.OMP.DP.LF  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\hipace.NOMPI.OMP.DP.LF.exe exit 1  # [win]
    # smoke tests: execute
    - ./test.sh      # [unix and build_platform == target_platform]
    - call test.bat  # [win]

about:
  home: https://hipace.readthedocs.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: license.txt
  summary: Highly efficient Plasma Accelerator Emulation, quasistatic particle-in-cell code

  description: |
    HiPACE++ is an open-source portable GPU-capable quasistatic
    particle-in-cell code for wakefield acceleration written in C++. It is a
    full re-writing of the legacy code HiPACE, the Highly efficient Plasma
    ACcelerator Emulator.

  doc_url: https://hipace.readthedocs.io
  dev_url: https://github.com/Hi-PACE/hipace

extra:
  recipe-maintainers:
    - AlexanderSinn
    - ax3l
    - MaxThevenet
    - SeverinDiederichs
